// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.Popups;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Content.Shared._EstacaoPirata.Cards.Card;
using Content.Shared._EstacaoPirata.Cards.Stack;

namespace Content.Client._EstacaoPirata.Cards.Hand.UI;

[GenerateTypedNameReferences]
public sealed partial class CardHandMenu : RadialMenu
{
    [Dependency] private EntityManager _entManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly SharedPopupSystem _popup;

    public event Action<NetEntity>? CardHandDrawMessageAction;

    private EntityUid _owner;

    public CardHandMenu(EntityUid owner, CardHandMenuBoundUserInterface bui)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _entManager.System<SpriteSystem>();
        _popup = _entManager.System<SharedPopupSystem>();

        _owner = owner;

        // Find the main radial container
        var main = FindControl<RadialContainer>("Main");

        if (!_entManager.TryGetComponent<CardStackComponent>(owner, out var stack))
            return;

        foreach (var card in stack.Cards)
        {
            if (_playerManager.LocalSession == null)
                return;
            if (!_entManager.TryGetComponent<CardComponent>(card, out var cardComp))
                return;

            // Wega: это меню видит ТОЛЬКО владелец руки, поэтому здесь карты всегда лицом вверх —
            // даже когда веер перевёрнут рубашкой к столу. Иначе в карты нельзя играть: чтобы
            // увидеть свои номиналы, приходилось разворачивать веер на виду у соперника.
            // Чужим клиентам карты в руке вообще не отправляются (лежат в контейнере игрока),
            // так что подсмотреть отсюда нечего.
            var cardName = !string.IsNullOrEmpty(cardComp.Name)
                ? Loc.GetString(cardComp.Name)
                : _entManager.TryGetComponent<MetaDataComponent>(card, out var metadata)
                    ? metadata.EntityName
                    : string.Empty;

            var button = new CardMenuButton()
            {
                SetSize = new Vector2(64f, 64f),
                ToolTip = cardName,
            };

            // Лицевую сторону берём из FrontSprite (его клиент собирает при старте компонента),
            // а не из текущего спрайта: у перевёрнутой карты текущий — рубашка.
            var face = cardComp.FrontSprite.Count > 0
                ? _spriteSystem.Frame0(cardComp.FrontSprite[^1])
                : _entManager.TryGetComponent<SpriteComponent>(card, out var sprite) ? sprite.Icon?.Default : null;

            if (face != null)
            {
                var tex = new TextureRect()
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = face,
                    TextureScale = new Vector2(2f, 2f),
                };

                button.AddChild(tex);
            }

            main.AddChild(button);

            button.OnButtonUp += _ =>
            {
                CardHandDrawMessageAction?.Invoke(_entManager.GetNetEntity(card));
                Close();
            };
        }

        CardHandDrawMessageAction += bui.SendCardHandDrawMessage;
    }
}

public sealed class CardMenuButton : RadialMenuButtonWithSector
{
    public CardMenuButton()
    {

    }
}
