using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Wega.Duel;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Wega.Duel;

[GenerateTypedNameReferences]
public sealed partial class ArenaLoadoutWindow : RadialMenu
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite;

    public event Action<ProtoId<ArenaLoadoutPrototype>>? OnLoadoutSelected;
    private List<ProtoId<ArenaLoadoutPrototype>> _loadouts = new();

    public ArenaLoadoutWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entMan.System<SpriteSystem>();
    }

    public void Populate(ArenaLoadoutSelectionState state)
    {
        MainContainer.RemoveAllChildren();
        _loadouts = state.AvailableLoadouts;

        foreach (var loadoutId in _loadouts)
        {
            if (!_prototype.TryIndex(loadoutId, out var loadout))
                continue;

            var button = CreateLoadoutButton(loadout);
            MainContainer.AddChild(button);
        }
    }

    private RadialMenuContextualCentralTextureButton CreateLoadoutButton(ArenaLoadoutPrototype loadout)
    {
        var button = new RadialMenuContextualCentralTextureButton
        {
            ToolTip = $"{Loc.GetString(loadout.Name)}\n{Loc.GetString(loadout.Description)}",
            SetSize = new Vector2(80, 80),
        };

        button.StyleClasses.Add("RadialMenuButton");

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center
        };

        if (loadout.Icon != null)
        {
            var icon = new TextureRect
            {
                Texture = _sprite.Frame0(loadout.Icon),
                Stretch = TextureRect.StretchMode.KeepCentered,
                SetSize = new Vector2(48, 48)
            };
            container.AddChild(icon);
        }
        else if (loadout.Contents.Count > 0 && _prototype.TryIndex<EntityPrototype>(loadout.Contents[0].EntityId, out var firstItem))
        {
            var entityView = new EntityPrototypeView
            {
                Scale = new Vector2(1.5f, 1.5f),
                SetSize = new Vector2(48, 48),
                Margin = new Thickness(2)
            };
            entityView.SetPrototype(firstItem.ID);
            container.AddChild(entityView);
        }

        button.AddChild(container);
        button.OnPressed += _ => OnLoadoutSelected?.Invoke(loadout.ID);

        return button;
    }
}
