using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client.MediaPlayer;
using Content.Shared.CCVar;
using Content.Shared.MediaPlayer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.StylesheetHelpers;

namespace Content.Client._Wega.MediaPlayer.UI;

[GenerateTypedNameReferences]
public sealed partial class MediaPlayerWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IResourceCache _resCache = default!;
    [Dependency] private IUserInterfaceManager _ui = default!;

    private const string RoundedButtonTex = "/Textures/Interface/Nano/rounded_button.svg.96dpi.png";
    private const string PanelTex = "/Textures/Interface/Nano/black_panel_dark_thin_border.png";
    private const string NoteTex = "/Textures/_Wega/Interface/MediaPlayer/note.png";
    private Texture _btnTex = default!;
    private Texture _noteTex = default!;

    private static readonly Color SearchingColor = Color.FromHex("#E6B32E"); // gold
    private static readonly Color WorkingColor = Color.FromHex("#5DBEE2");   // cyan
    private static readonly Color ErrorColor = Color.FromHex("#E24B4A");     // red

    // Player styling — kept in code so the flat colored look matches the designer mockup.
    private static readonly Color AccentColor = Color.FromHex("#38C6D6");    // progress fill
    private static readonly Color BtnNeutral = Color.FromHex("#39424F");
    private static readonly Color BtnActive = Color.FromHex("#2B5B6B");      // toggled-on tint
    private static readonly Color BtnGreen = Color.FromHex("#3FB950");
    private static readonly Color BtnRed = Color.FromHex("#E24B4A");
    private static readonly Color BtnTextLight = Color.FromHex("#D6DDE3");
    private static readonly Color BtnTextRed = Color.FromHex("#FFECEC");
    private static readonly Color GrabberColor = Color.FromHex("#EAF2F6");

    private readonly MediaPlayerSystem _mediaPlayer;
    private List<MediaSearchResult> _results = [];

    private const int PageSize = 10;
    private int _currentPage;

    // Remembers the pre-mute volume so unmuting restores it.
    private float _volumeBeforeMute = 0.5f;

    // Окно открыто с телевизора: play/stop управляют ТВ-клипом, музыкальные секции скрыты.
    private bool _tvMode;

    public MediaPlayerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mediaPlayer = _entMan.System<MediaPlayerSystem>();

        SearchButton.OnPressed += _ => Search();
        SearchField.OnTextEntered += _ => Search();
        PlayPauseButton.OnPressed += _ => PlayOrPause();
        PlayUrlButton.OnPressed += _ => PlayUrl();
        StopButton.OnPressed += _ =>
        {
            if (_tvMode)
                _mediaPlayer.RequestTvStop();
            else
                _mediaPlayer.RequestStop();
        };
        PrevPageButton.OnPressed += _ => ChangePage(-1);
        NextPageButton.OnPressed += _ => ChangePage(1);
        EnqueueButton.OnPressed += _ => EnqueueSelected();

        ResultsList.OnItemSelected += _ => SetResultSelected(true);
        ResultsList.OnItemDeselected += _ => SetResultSelected(false);

        // Queue: clicking an entry removes it; the clear button wipes the whole queue.
        QueueList.OnItemSelected += args => _mediaPlayer.RequestQueueRemove(args.ItemIndex);
        ClearQueueButton.OnPressed += _ => _mediaPlayer.RequestQueueRemove(-1);

        // Repeat / shuffle are server-side modes; report the button state on toggle.
        RepeatButton.OnToggled += _ => SendMode();
        ShuffleButton.OnToggled += _ => SendMode();

        // Seek: apply once the grabber is released, so we don't spam the server mid-drag.
        ProgressSlider.OnReleased += _ => _mediaPlayer.RequestSeek(ProgressSlider.Value);

        MuteButton.OnToggled += _ => ToggleMute();

        VolumeSlider.Value = _cfg.GetCVar(WegaCVars.MediaPlayerVolume);
        UpdateVolumeLabel(VolumeSlider.Value);
        VolumeSlider.OnValueChanged += slider =>
        {
            _cfg.SetCVar(WegaCVars.MediaPlayerVolume, slider.Value);
            UpdateVolumeLabel(slider.Value);
            // Raising the volume by hand cancels a mute.
            if (slider.Value > 0.001f && MuteButton.Pressed)
                MuteButton.Pressed = false;
        };

        _mediaPlayer.SearchReceived += OnSearchReceived;
        _mediaPlayer.StatusReceived += OnStatusReceived;
        _mediaPlayer.StateUpdated += UpdateNowPlaying;
        _mediaPlayer.TvStateUpdated += UpdateNowPlaying;
        _mediaPlayer.ThumbnailLoaded += OnThumbnailLoaded;
        _mediaPlayer.QueueUpdated += RefreshQueue;

        ApplyStyle();
        UpdateNowPlaying();
        RefreshQueue();

        // Restore previous search results when reopening the window.
        _results = _mediaPlayer.LastSearchResults;
        if (_results.Count > 0)
        {
            StatusLabel.Text = Loc.GetString("ui-media-player-results", ("count", _results.Count));
            PopulateResultsList();
        }
        else
        {
            UpdatePagination();
        }

        UpdateEmptyHint();
    }

    /// <summary>
    /// Rounded, colored styling built from the game's own 9-slice textures so the in-game player
    /// reads like the design mockup: rounded accent-filled progress slider, rounded colored buttons,
    /// and a rounded card behind the transport.
    /// </summary>
    private void ApplyStyle()
    {
        _btnTex = _resCache.GetResource<TextureResource>(RoundedButtonTex).Texture;
        _noteTex = _resCache.GetResource<TextureResource>(NoteTex).Texture;
        var panelTex = _resCache.GetResource<TextureResource>(PanelTex).Texture;

        // Now-playing card — rounded dark panel.
        var card = new StyleBoxTexture { Texture = panelTex, Modulate = Color.FromHex("#2B323D") };
        card.SetPatchMargin(StyleBox.Margin.All, 3);
        card.SetContentMarginOverride(StyleBox.Margin.All, 12);
        NowPlayingPanel.PanelOverride = card;

        // Results panel — dark box, doubles as the empty-state backdrop.
        var resultsBox = new StyleBoxTexture { Texture = panelTex, Modulate = Color.FromHex("#1D232C") };
        resultsBox.SetPatchMargin(StyleBox.Margin.All, 3);
        ResultsPanel.PanelOverride = resultsBox;

        // Search field — rounded dark box to match the card and buttons.
        var field = new StyleBoxTexture { Texture = panelTex, Modulate = Color.FromHex("#1D232C") };
        field.SetPatchMargin(StyleBox.Margin.All, 3);
        field.SetContentMarginOverride(StyleBox.Margin.Horizontal, 10);
        field.SetContentMarginOverride(StyleBox.Margin.Vertical, 6);
        SearchField.StyleBoxOverride = field;

        // Progress slider — rounded pill: dark channel + accent fill + light grabber.
        ProgressSlider.BackgroundStyleBoxOverride = BarBox(Color.FromHex("#12161C"));
        ProgressSlider.FillStyleBoxOverride = BarBox(AccentColor);
        ProgressSlider.GrabberStyleBoxOverride = BarBox(GrabberColor);

        // Transport + search buttons — rounded, tinted.
        StyleButton(SearchButton, BtnNeutral, BtnTextLight);
        StyleButton(PlayUrlButton, BtnNeutral, BtnTextLight);
        StyleButton(PlayPauseButton, BtnGreen, Color.White);
        StyleButton(StopButton, BtnRed, BtnTextRed);
        StyleButton(EnqueueButton, BtnNeutral, BtnTextLight);
        StyleButton(ClearQueueButton, BtnNeutral, BtnTextLight);

        // Toggle buttons recolor when active; refresh their look now and on every state change.
        StyleToggle(RepeatButton);
        StyleToggle(ShuffleButton);
        StyleToggle(MuteButton);

        // Result + queue lists — teal selection like the mockup.
        var listRule = Element<ItemList>()
            .Prop(ItemList.StylePropertyBackground, new StyleBoxFlat { BackgroundColor = Color.FromHex("#1D232C") })
            .Prop(ItemList.StylePropertyItemBackground, new StyleBoxFlat { BackgroundColor = Color.Transparent })
            .Prop(ItemList.StylePropertyDisabledItemBackground, new StyleBoxFlat { BackgroundColor = Color.FromHex("#12161C") })
            .Prop(ItemList.StylePropertySelectedItemBackground, new StyleBoxFlat { BackgroundColor = Color.FromHex("#2B5B6B") });

        var existingRules = _ui.Stylesheet?.Rules ?? Array.Empty<StyleRule>();
        var sheet = new Stylesheet(existingRules.Append(listRule).ToArray());
        ResultsList.Stylesheet = sheet;
        QueueList.Stylesheet = sheet;

        // Now-playing title + empty hint.
        NowPlayingLabel.FontColorOverride = Color.White;
        EmptyHintLabel.FontColorOverride = Color.FromHex("#6B7683");
    }

    private StyleBoxTexture BarBox(Color color)
    {
        var box = new StyleBoxTexture { Texture = _btnTex, Modulate = color };
        box.SetPatchMargin(StyleBox.Margin.All, 5);
        return box;
    }

    private StyleBoxTexture ButtonBox(Color color)
    {
        var box = new StyleBoxTexture { Texture = _btnTex, Modulate = color };
        box.SetPatchMargin(StyleBox.Margin.All, 5);
        box.SetContentMarginOverride(StyleBox.Margin.Vertical, 6);
        box.SetContentMarginOverride(StyleBox.Margin.Horizontal, 12);
        return box;
    }

    private void StyleButton(Button button, Color color, Color textColor)
    {
        button.StyleBoxOverride = ButtonBox(color);
        button.Label.FontColorOverride = textColor;

        var hover = new Color(
            Math.Min(1f, color.R + 0.12f),
            Math.Min(1f, color.G + 0.12f),
            Math.Min(1f, color.B + 0.12f));

        button.OnMouseEntered += _ => { if (!button.Disabled) button.StyleBoxOverride = ButtonBox(hover); };
        button.OnMouseExited += _ => button.StyleBoxOverride = ButtonBox(color);
    }

    /// <summary>
    /// Styles a toggle button so its background follows the pressed state. Repaints immediately and
    /// whenever it's toggled; call <see cref="RepaintToggle"/> after changing Pressed in code.
    /// </summary>
    private void StyleToggle(Button button)
    {
        button.Label.FontColorOverride = BtnTextLight;
        RepaintToggle(button);
        button.OnToggled += _ => RepaintToggle(button);
    }

    private void RepaintToggle(Button button)
    {
        button.StyleBoxOverride = ButtonBox(button.Pressed ? BtnActive : BtnNeutral);
    }

    /// <summary>
    /// Toggles a styled button's enabled state, dimming it while disabled (the flat stylebox
    /// override doesn't grey out on its own).
    /// </summary>
    private static void SetEnabled(Button button, bool enabled)
    {
        button.Disabled = !enabled;
        // Keep the color clearly readable even when disabled (matches the always-vivid mockup).
        button.Modulate = enabled ? Color.White : new Color(0.82f, 0.82f, 0.82f);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _mediaPlayer.SearchReceived -= OnSearchReceived;
        _mediaPlayer.StatusReceived -= OnStatusReceived;
        _mediaPlayer.StateUpdated -= UpdateNowPlaying;
        _mediaPlayer.TvStateUpdated -= UpdateNowPlaying;
        _mediaPlayer.ThumbnailLoaded -= OnThumbnailLoaded;
        _mediaPlayer.QueueUpdated -= RefreshQueue;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_tvMode)
            return; // прогресс/тайминги относятся к музыке и в ТВ-режиме скрыты

        if (!_mediaPlayer.IsPlaying)
        {
            ProgressSlider.SetValueWithoutEvent(0f);
            return;
        }

        var position = _mediaPlayer.CurrentPosition;
        var duration = _mediaPlayer.CurrentDuration;

        ProgressSlider.MaxValue = duration > 0 ? duration : 1f;

        // While the user is dragging the grabber, leave its value alone and show the target time.
        if (ProgressSlider.Grabbed)
        {
            TimeCurrentLabel.Text = FormatTime(ProgressSlider.Value);
        }
        else
        {
            ProgressSlider.SetValueWithoutEvent(Math.Clamp(position, 0f, ProgressSlider.MaxValue));
            TimeCurrentLabel.Text = FormatTime(position);
        }

        TimeTotalLabel.Text = FormatTime(duration);
    }

    private void Search()
    {
        var query = SearchField.Text.Trim();
        if (query.Length == 0)
            return;

        SetSearching(true);
        _mediaPlayer.RequestSearch(query);
    }

    private void SetSearching(bool searching)
    {
        SearchButton.Disabled = searching;
        SearchButton.Text = Loc.GetString(searching
            ? "ui-media-player-searching-button"
            : "ui-media-player-search-button");

        if (searching)
        {
            StatusLabel.Text = Loc.GetString("ui-media-player-searching");
            StatusLabel.FontColorOverride = SearchingColor;
        }
        else
        {
            StatusLabel.FontColorOverride = null;
        }
    }

    /// <summary>
    /// Переключает окно между музыкальным и ТВ-режимом. В ТВ-режиме поиск тот же, но
    /// «Играть»/«По ссылке»/«Стоп» шлют клип на экраны; очередь/повтор/перемотка — только для музыки.
    /// </summary>
    public void SetTvMode(bool tv)
    {
        _tvMode = tv;
        Title = Loc.GetString(tv ? "ui-media-player-title-tv" : "ui-media-player-title");

        EnqueueButton.Visible = !tv;
        RepeatButton.Visible = !tv;
        ShuffleButton.Visible = !tv;
        QueueHeaderLabel.Visible = !tv;
        ClearQueueButton.Visible = !tv;
        ProgressSlider.Visible = !tv;
        TimeCurrentLabel.Visible = !tv;
        TimeTotalLabel.Visible = !tv;

        RefreshQueue();
        UpdateNowPlaying();
    }

    private void PlayOrPause()
    {
        if (_tvMode)
        {
            // Клип уже крутится — кнопка работает как пауза/продолжение, как и у музыки.
            if (_mediaPlayer.TvHasClip)
                _mediaPlayer.RequestTvPause();
            else
                PlaySelected();
            return;
        }

        var state = _mediaPlayer.LastState;
        if (state?.TrackId != null)
        {
            // Track is loaded: toggle pause/resume on the server.
            _mediaPlayer.RequestPause();
            return;
        }

        PlaySelected();
    }

    private void PlaySelected()
    {
        foreach (var item in ResultsList.GetSelected())
        {
            var index = ResultsList.IndexOf(item) + _currentPage * PageSize;
            if (index >= 0 && index < _results.Count)
            {
                if (_tvMode)
                    _mediaPlayer.RequestTvPlay(_results[index].Id);
                else
                    _mediaPlayer.RequestPlay(_results[index].Id);
            }
            return;
        }
    }

    private void PlayUrl()
    {
        var url = SearchField.Text.Trim();
        if (url.Length == 0)
            return;

        if (_tvMode)
            _mediaPlayer.RequestTvPlay(url);
        else
            _mediaPlayer.RequestPlay(url);
    }

    private void EnqueueSelected()
    {
        foreach (var item in ResultsList.GetSelected())
        {
            var index = ResultsList.IndexOf(item) + _currentPage * PageSize;
            if (index >= 0 && index < _results.Count)
            {
                var result = _results[index];
                _mediaPlayer.RequestEnqueue(result.Id, MediaPlayerSystem.SanitizeTitle(result.Title));
            }
            return;
        }
    }

    /// <summary>Enables/disables the buttons that act on the selected search result.</summary>
    private void SetResultSelected(bool selected)
    {
        EnqueueButton.Disabled = !selected;

        // ТВ-режим: «Играть» действует только на выбранный результат, паузы у ТВ нет.
        if (_tvMode)
        {
            SetEnabled(PlayPauseButton, selected);
            return;
        }

        // Don't disable play/pause while a track is loaded — it still controls that track.
        if (selected || _mediaPlayer.LastState?.TrackId != null)
            SetEnabled(PlayPauseButton, true);
        else
            SetEnabled(PlayPauseButton, false);
    }

    private void SendMode()
    {
        _mediaPlayer.RequestMode(RepeatButton.Pressed, ShuffleButton.Pressed);
    }

    private void ToggleMute()
    {
        RepaintToggle(MuteButton);

        if (MuteButton.Pressed)
        {
            _volumeBeforeMute = VolumeSlider.Value > 0.001f ? VolumeSlider.Value : _volumeBeforeMute;
            VolumeSlider.Value = 0f; // fires OnValueChanged → applies to the cvar + label
        }
        else
        {
            VolumeSlider.Value = _volumeBeforeMute > 0.001f ? _volumeBeforeMute : 0.5f;
        }
    }

    private void OnSearchReceived(MediaPlayerSearchResponseEvent ev)
    {
        ResultsList.Clear();
        SetResultSelected(false);
        _results = _mediaPlayer.LastSearchResults;
        _currentPage = 0;
        SetSearching(false);

        if (ev.Error != null)
        {
            StatusLabel.Text = ev.Error;
            StatusLabel.FontColorOverride = ErrorColor;
            UpdatePagination();
            UpdateEmptyHint();
            return;
        }

        StatusLabel.Text = Loc.GetString("ui-media-player-results", ("count", _results.Count));
        PopulateResultsList();
    }

    private void PopulateResultsList()
    {
        ResultsList.Clear();

        var pageCount = Math.Max(1, (int)MathF.Ceiling(_results.Count / (float)PageSize));
        _currentPage = Math.Clamp(_currentPage, 0, pageCount - 1);

        var start = _currentPage * PageSize;
        var end = Math.Min(start + PageSize, _results.Count);
        for (var i = start; i < end; i++)
        {
            var result = _results[i];
            var title = MediaPlayerSystem.SanitizeTitle(result.Title);
            var uploader = result.Uploader.Length > 0
                ? $" — {MediaPlayerSystem.SanitizeTitle(result.Uploader)}"
                : "";
            var text = $"[{FormatTime(result.DurationSeconds)}] {title}{uploader}";
            var icon = _mediaPlayer.GetThumbnail(result.Id);
            ResultsList.AddItem(text, icon);
        }

        UpdatePagination();
        UpdateEmptyHint();
    }

    private void ChangePage(int delta)
    {
        var pageCount = Math.Max(1, (int)MathF.Ceiling(_results.Count / (float)PageSize));
        var newPage = Math.Clamp(_currentPage + delta, 0, pageCount - 1);
        if (newPage == _currentPage)
            return;

        _currentPage = newPage;
        PopulateResultsList();
    }

    private void UpdatePagination()
    {
        var pageCount = Math.Max(1, (int)MathF.Ceiling(_results.Count / (float)PageSize));
        PageLabel.Text = _results.Count > 0
            ? $"{_currentPage + 1} / {pageCount}"
            : "-";
        PrevPageButton.Disabled = _currentPage <= 0;
        NextPageButton.Disabled = _currentPage >= pageCount - 1;
    }

    private void UpdateEmptyHint()
    {
        EmptyHintLabel.Visible = _results.Count == 0;
    }

    private void OnThumbnailLoaded(string id)
    {
        // Late cover for the now-playing track.
        if (_mediaPlayer.LastState?.TrackId == id)
            UpdateCover(id);

        var icon = _mediaPlayer.GetThumbnail(id);
        if (icon == null)
            return;

        for (var i = 0; i < _results.Count; i++)
        {
            if (_results[i].Id != id)
                continue;

            var start = _currentPage * PageSize;
            var end = Math.Min(start + PageSize, _results.Count);
            if (i < start || i >= end)
                return;

            var item = ResultsList[i - start];
            if (item != null)
                item.Icon = icon;
            return;
        }
    }

    private void OnStatusReceived(MediaPlayerStatusEvent ev)
    {
        StatusLabel.Text = ev.Message;
        StatusLabel.FontColorOverride = ev.IsError ? ErrorColor : WorkingColor;
    }

    private void UpdateNowPlaying()
    {
        // ТВ-режим: карточка не отражает музыкальный трек — показываем подсказку по ТВ.
        if (_tvMode)
        {
            NowPlayingLabel.Text = Loc.GetString("ui-media-player-tv-hint");
            UpdateCover(null);
            SetEnabled(StopButton, true); // «Стоп» гасит экраны в любой момент

            if (_mediaPlayer.TvLoading)
            {
                // Пока клип едет по сети — показываем процент, кнопку блокируем.
                StatusLabel.Text = Loc.GetString("ui-media-player-tv-loading",
                    ("percent", (int)(_mediaPlayer.TvProgress * 100f)));
                StatusLabel.FontColorOverride = WorkingColor;
                PlayPauseButton.Text = Loc.GetString("ui-media-player-play-button");
                SetEnabled(PlayPauseButton, false);
                return;
            }

            if (_mediaPlayer.TvHasClip)
            {
                // Клип крутится: кнопка становится паузой/продолжением.
                PlayPauseButton.Text = Loc.GetString(_mediaPlayer.TvPaused
                    ? "ui-media-player-resume-button"
                    : "ui-media-player-pause-button");
                SetEnabled(PlayPauseButton, true);
                return;
            }

            PlayPauseButton.Text = Loc.GetString("ui-media-player-play-button");
            SetEnabled(PlayPauseButton, ResultsList.GetSelected().Any());
            return;
        }

        var state = _mediaPlayer.LastState;

        // Nothing loaded.
        if (state?.TrackId == null)
        {
            NowPlayingLabel.Text = Loc.GetString("ui-media-player-nothing");
            TimeCurrentLabel.Text = FormatTime(0);
            TimeTotalLabel.Text = FormatTime(0);
            ProgressSlider.SetValueWithoutEvent(0f);
            UpdateCover(null);
            SetEnabled(StopButton, false);
            // Play/pause stays enabled if a search result is selected (so it can start it).
            SetResultSelected(ResultsList.GetSelected().Any());
            PlayPauseButton.Text = Loc.GetString("ui-media-player-play-button");
            return;
        }

        // A track is loaded (playing or paused): clear the transient status line.
        StatusLabel.Text = string.Empty;

        NowPlayingLabel.Text = MediaPlayerSystem.SanitizeTitle(state.Title);
        TimeTotalLabel.Text = FormatTime(state.Duration);
        UpdateCover(state.TrackId);
        SetEnabled(PlayPauseButton, true);
        SetEnabled(StopButton, true);
        PlayPauseButton.Text = Loc.GetString(state.Playing
            ? "ui-media-player-pause-button"
            : "ui-media-player-resume-button");
    }

    /// <summary>
    /// Shows the track's cover in the now-playing card, falling back to the note icon when the
    /// thumbnail hasn't been downloaded (e.g. a track played by direct URL).
    /// </summary>
    private void UpdateCover(string? trackId)
    {
        var cover = trackId != null ? _mediaPlayer.GetThumbnail(trackId) : null;
        NoteIcon.Texture = cover ?? _noteTex;
    }

    private void RefreshQueue()
    {
        // Reflect the server's mode state without firing OnToggled, then repaint.
        RepeatButton.Pressed = _mediaPlayer.Repeat;
        ShuffleButton.Pressed = _mediaPlayer.Shuffle;
        RepaintToggle(RepeatButton);
        RepaintToggle(ShuffleButton);

        QueueList.Clear();
        var queue = _mediaPlayer.Queue;
        foreach (var item in queue)
        {
            var title = item.Title.Length > 0 ? item.Title : item.IdOrUrl;
            QueueList.AddItem(MediaPlayerSystem.SanitizeTitle(title));
        }

        // Collapse the list entirely when empty so it doesn't reserve a dead black band.
        // В ТВ-режиме очередь музыкальная и не показывается вовсе.
        QueueList.Visible = !_tvMode && queue.Count > 0;
        ClearQueueButton.Disabled = queue.Count == 0;
        QueueHeaderLabel.Text = queue.Count == 0
            ? Loc.GetString("ui-media-player-queue-empty")
            : Loc.GetString("ui-media-player-queue-count", ("count", queue.Count));
    }

    private void UpdateVolumeLabel(float value)
    {
        VolumePercentLabel.Text = $"{(int)MathF.Round(value * 100f)}%";
    }

    private static string FormatTime(float seconds)
    {
        var span = TimeSpan.FromSeconds(Math.Max(0f, seconds));
        return span.TotalHours >= 1
            ? $"{(int)span.TotalHours}:{span.Minutes:00}:{span.Seconds:00}"
            : $"{span.Minutes}:{span.Seconds:00}";
    }
}
