using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client.MediaPlayer;
using Content.Shared.CCVar;
using Content.Shared.MediaPlayer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._Wega.MediaPlayer.UI;

[GenerateTypedNameReferences]
public sealed partial class MediaPlayerWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entMan = default!;

    private static readonly Color SearchingColor = Color.FromHex("#E6B32E"); // gold
    private static readonly Color WorkingColor = Color.FromHex("#5DBEE2");   // cyan
    private static readonly Color ErrorColor = Color.FromHex("#E24B4A");     // red

    private readonly MediaPlayerSystem _mediaPlayer;
    private List<MediaSearchResult> _results = [];

    public MediaPlayerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mediaPlayer = _entMan.System<MediaPlayerSystem>();

        SearchButton.OnPressed += _ => Search();
        SearchField.OnTextEntered += _ => Search();
        PlayButton.OnPressed += _ => PlaySelected();
        PlayUrlButton.OnPressed += _ => PlayUrl();
        PauseButton.OnPressed += _ => _mediaPlayer.RequestPause();
        StopButton.OnPressed += _ => _mediaPlayer.RequestStop();

        ResultsList.OnItemSelected += _ => PlayButton.Disabled = false;
        ResultsList.OnItemDeselected += _ => PlayButton.Disabled = true;

        VolumeSlider.Value = _cfg.GetCVar(WegaCVars.MediaPlayerVolume);
        UpdateVolumeLabel(VolumeSlider.Value);
        VolumeSlider.OnValueChanged += slider =>
        {
            _cfg.SetCVar(WegaCVars.MediaPlayerVolume, slider.Value);
            UpdateVolumeLabel(slider.Value);
        };

        _mediaPlayer.SearchReceived += OnSearchReceived;
        _mediaPlayer.StatusReceived += OnStatusReceived;
        _mediaPlayer.StateUpdated += UpdateNowPlaying;

        UpdateNowPlaying();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _mediaPlayer.SearchReceived -= OnSearchReceived;
        _mediaPlayer.StatusReceived -= OnStatusReceived;
        _mediaPlayer.StateUpdated -= UpdateNowPlaying;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_mediaPlayer.IsPlaying)
        {
            ProgressBar.Value = 0f;
            return;
        }

        var position = _mediaPlayer.CurrentPosition;
        var duration = _mediaPlayer.CurrentDuration;

        ProgressBar.MaxValue = duration > 0 ? duration : 1f;
        ProgressBar.Value = Math.Clamp(position, 0f, ProgressBar.MaxValue);

        TimeCurrentLabel.Text = FormatTime(position);
        TimeTotalLabel.Text = FormatTime(duration);
    }

    private void Search()
    {
        var query = SearchField.Text.Trim();
        if (query.Length == 0)
            return;

        SetSearching(true);
        _mediaPlayer.RequestSearch(query);
    }

    private void SetSearching(bool searching)
    {
        SearchButton.Disabled = searching;
        SearchButton.Text = Loc.GetString(searching
            ? "ui-media-player-searching-button"
            : "ui-media-player-search-button");

        if (searching)
        {
            StatusLabel.Text = Loc.GetString("ui-media-player-searching");
            StatusLabel.FontColorOverride = SearchingColor;
        }
        else
        {
            StatusLabel.FontColorOverride = null;
        }
    }

    private void PlaySelected()
    {
        foreach (var item in ResultsList.GetSelected())
        {
            var index = ResultsList.IndexOf(item);
            if (index >= 0 && index < _results.Count)
                _mediaPlayer.RequestPlay(_results[index].Id);
            return;
        }
    }

    private void PlayUrl()
    {
        var url = SearchField.Text.Trim();
        if (url.Length == 0)
            return;

        _mediaPlayer.RequestPlay(url);
    }

    private void OnSearchReceived(MediaPlayerSearchResponseEvent ev)
    {
        ResultsList.Clear();
        PlayButton.Disabled = true;
        _results = ev.Results;
        SetSearching(false);

        if (ev.Error != null)
        {
            StatusLabel.Text = ev.Error;
            StatusLabel.FontColorOverride = ErrorColor;
            return;
        }

        StatusLabel.Text = Loc.GetString("ui-media-player-results", ("count", ev.Results.Count));

        foreach (var result in ev.Results)
        {
            var title = MediaPlayerSystem.SanitizeTitle(result.Title);
            var uploader = result.Uploader.Length > 0
                ? $" — {MediaPlayerSystem.SanitizeTitle(result.Uploader)}"
                : "";
            ResultsList.AddItem($"[{FormatTime(result.DurationSeconds)}] {title}{uploader}");
        }
    }

    private void OnStatusReceived(MediaPlayerStatusEvent ev)
    {
        StatusLabel.Text = ev.Message;
        StatusLabel.FontColorOverride = ev.IsError ? ErrorColor : WorkingColor;
    }

    private void UpdateNowPlaying()
    {
        var state = _mediaPlayer.LastState;

        // Nothing loaded.
        if (state?.TrackId == null)
        {
            NowPlayingLabel.Text = Loc.GetString("ui-media-player-nothing");
            TimeCurrentLabel.Text = FormatTime(0);
            TimeTotalLabel.Text = FormatTime(0);
            ProgressBar.Value = 0f;
            PauseButton.Disabled = true;
            StopButton.Disabled = true;
            PauseButton.Text = Loc.GetString("ui-media-player-pause-button");
            return;
        }

        // A track is loaded (playing or paused): clear the transient status line.
        StatusLabel.Text = string.Empty;

        NowPlayingLabel.Text = MediaPlayerSystem.SanitizeTitle(state.Title);
        TimeTotalLabel.Text = FormatTime(state.Duration);
        PauseButton.Disabled = false;
        StopButton.Disabled = false;
        PauseButton.Text = Loc.GetString(state.Playing
            ? "ui-media-player-pause-button"
            : "ui-media-player-resume-button");
    }

    private void UpdateVolumeLabel(float value)
    {
        VolumePercentLabel.Text = $"{(int)MathF.Round(value * 100f)}%";
    }

    private static string FormatTime(float seconds)
    {
        var span = TimeSpan.FromSeconds(Math.Max(0f, seconds));
        return span.TotalHours >= 1
            ? $"{(int)span.TotalHours}:{span.Minutes:00}:{span.Seconds:00}"
            : $"{span.Minutes}:{span.Seconds:00}";
    }
}
