using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client._Wega.MediaPlayer.UI;

/// <summary>
/// Small HUD indicator that shows the currently playing media-player track.
/// Clicking it opens the media player window (see <see cref="ClickAction"/>).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MediaPlayerIndicator : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    private const int MaxTitleLength = 40;
    private const string PanelTex = "/Textures/Interface/Nano/black_panel_dark_thin_border.png";

    /// <summary>Invoked when the badge is clicked. Wired by the controller to open the window.</summary>
    public Action? ClickAction;

    public MediaPlayerIndicator()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        DefaultCursorShape = CursorShape.Hand;

        // Compact rounded badge that hugs the icon + title. The vanilla "BackgroundPanel" styleclass
        // carries a min-size and heavy padding, which left a big frame around the tiny note.
        var tex = _resCache.GetResource<TextureResource>(PanelTex).Texture;
        var box = new StyleBoxTexture { Texture = tex, Modulate = Color.FromHex("#242A33F0") };
        box.SetPatchMargin(StyleBox.Margin.All, 3);
        box.SetContentMarginOverride(StyleBox.Margin.Vertical, 3);
        box.SetContentMarginOverride(StyleBox.Margin.Horizontal, 6);
        BackgroundPanel.PanelOverride = box;
    }

    public void SetTrack(string title)
    {
        if (title.Length > MaxTitleLength)
            title = title[..MaxTitleLength] + "…";

        TitleLabel.Text = title;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        ClickAction?.Invoke();
        args.Handle();
    }
}
