using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client.MediaPlayer;
using Content.Shared.CCVar;
using Content.Shared.MediaPlayer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.StylesheetHelpers;

namespace Content.Client._Wega.MediaPlayer.UI;

[GenerateTypedNameReferences]
public sealed partial class MediaPlayerWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IResourceCache _resCache = default!;
    [Dependency] private IUserInterfaceManager _ui = default!;

    private const string RoundedButtonTex = "/Textures/Interface/Nano/rounded_button.svg.96dpi.png";
    private const string PanelTex = "/Textures/Interface/Nano/black_panel_dark_thin_border.png";
    private Texture _btnTex = default!;

    private static readonly Color SearchingColor = Color.FromHex("#E6B32E"); // gold
    private static readonly Color WorkingColor = Color.FromHex("#5DBEE2");   // cyan
    private static readonly Color ErrorColor = Color.FromHex("#E24B4A");     // red

    // Player styling — kept in code so the flat colored look matches the designer mockup.
    private static readonly Color AccentColor = Color.FromHex("#38C6D6");    // progress fill
    private static readonly Color BtnNeutral = Color.FromHex("#39424F");
    private static readonly Color BtnGreen = Color.FromHex("#3FB950");
    private static readonly Color BtnRed = Color.FromHex("#E24B4A");
    private static readonly Color BtnTextLight = Color.FromHex("#D6DDE3");
    private static readonly Color BtnTextGreen = Color.FromHex("#0B2912");
    private static readonly Color BtnTextRed = Color.FromHex("#FFECEC");

    private readonly MediaPlayerSystem _mediaPlayer;
    private List<MediaSearchResult> _results = [];

    public MediaPlayerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mediaPlayer = _entMan.System<MediaPlayerSystem>();

        SearchButton.OnPressed += _ => Search();
        SearchField.OnTextEntered += _ => Search();
        PlayPauseButton.OnPressed += _ => PlayOrPause();
        PlayUrlButton.OnPressed += _ => PlayUrl();
        StopButton.OnPressed += _ => _mediaPlayer.RequestStop();

        ResultsList.OnItemSelected += _ => SetEnabled(PlayPauseButton, true);
        ResultsList.OnItemDeselected += _ => SetEnabled(PlayPauseButton, false);

        VolumeSlider.Value = _cfg.GetCVar(WegaCVars.MediaPlayerVolume);
        UpdateVolumeLabel(VolumeSlider.Value);
        VolumeSlider.OnValueChanged += slider =>
        {
            _cfg.SetCVar(WegaCVars.MediaPlayerVolume, slider.Value);
            UpdateVolumeLabel(slider.Value);
        };

        _mediaPlayer.SearchReceived += OnSearchReceived;
        _mediaPlayer.StatusReceived += OnStatusReceived;
        _mediaPlayer.StateUpdated += UpdateNowPlaying;

        ApplyStyle();
        UpdateNowPlaying();

        // Restore previous search results when reopening the window.
        _results = _mediaPlayer.LastSearchResults;
        if (_results.Count > 0)
        {
            StatusLabel.Text = Loc.GetString("ui-media-player-results", ("count", _results.Count));
            PopulateResultsList();
        }
    }

    /// <summary>
    /// Rounded, colored styling built from the game's own 9-slice textures so the in-game player
    /// reads like the design mockup: rounded accent-filled progress bar, rounded colored buttons,
    /// and a rounded card behind the transport.
    /// </summary>
    private void ApplyStyle()
    {
        _btnTex = _resCache.GetResource<TextureResource>(RoundedButtonTex).Texture;
        var panelTex = _resCache.GetResource<TextureResource>(PanelTex).Texture;

        // Now-playing card — rounded dark panel.
        var card = new StyleBoxTexture { Texture = panelTex, Modulate = Color.FromHex("#2B323D") };
        card.SetPatchMargin(StyleBox.Margin.All, 3);
        card.SetContentMarginOverride(StyleBox.Margin.All, 12);
        NowPlayingPanel.PanelOverride = card;

        // Search field — rounded dark box to match the card and buttons.
        var field = new StyleBoxTexture { Texture = panelTex, Modulate = Color.FromHex("#1D232C") };
        field.SetPatchMargin(StyleBox.Margin.All, 3);
        field.SetContentMarginOverride(StyleBox.Margin.Horizontal, 10);
        field.SetContentMarginOverride(StyleBox.Margin.Vertical, 6);
        SearchField.StyleBoxOverride = field;

        // Progress bar — rounded pill: dark channel + accent fill.
        ProgressBar.BackgroundStyleBoxOverride = BarBox(Color.FromHex("#12161C"));
        ProgressBar.ForegroundStyleBoxOverride = BarBox(AccentColor);

        // Transport + search buttons — rounded, tinted.
        StyleButton(SearchButton, BtnNeutral, BtnTextLight);
        StyleButton(PlayUrlButton, BtnNeutral, BtnTextLight);
        StyleButton(PlayPauseButton, BtnGreen, Color.White);
        StyleButton(StopButton, BtnRed, BtnTextRed);

        // Result list — teal selection like the mockup.
        var listRule = Element<ItemList>()
            .Prop(ItemList.StylePropertyBackground, new StyleBoxFlat { BackgroundColor = Color.FromHex("#1D232C") })
            .Prop(ItemList.StylePropertyItemBackground, new StyleBoxFlat { BackgroundColor = Color.Transparent })
            .Prop(ItemList.StylePropertyDisabledItemBackground, new StyleBoxFlat { BackgroundColor = Color.FromHex("#12161C") })
            .Prop(ItemList.StylePropertySelectedItemBackground, new StyleBoxFlat { BackgroundColor = Color.FromHex("#2B5B6B") });

        var existingRules = _ui.Stylesheet?.Rules ?? Array.Empty<StyleRule>();
        ResultsList.Stylesheet = new Stylesheet(existingRules.Append(listRule).ToArray());

        // Now-playing title — white, bold heading.
        NowPlayingLabel.FontColorOverride = Color.White;
    }

    private StyleBoxTexture BarBox(Color color)
    {
        var box = new StyleBoxTexture { Texture = _btnTex, Modulate = color };
        box.SetPatchMargin(StyleBox.Margin.All, 5);
        return box;
    }

    private StyleBoxTexture ButtonBox(Color color)
    {
        var box = new StyleBoxTexture { Texture = _btnTex, Modulate = color };
        box.SetPatchMargin(StyleBox.Margin.All, 5);
        box.SetContentMarginOverride(StyleBox.Margin.Vertical, 6);
        box.SetContentMarginOverride(StyleBox.Margin.Horizontal, 12);
        return box;
    }

    private void StyleButton(Button button, Color color, Color textColor)
    {
        button.StyleBoxOverride = ButtonBox(color);
        button.Label.FontColorOverride = textColor;

        var hover = new Color(
            Math.Min(1f, color.R + 0.12f),
            Math.Min(1f, color.G + 0.12f),
            Math.Min(1f, color.B + 0.12f));

        button.OnMouseEntered += _ => { if (!button.Disabled) button.StyleBoxOverride = ButtonBox(hover); };
        button.OnMouseExited += _ => button.StyleBoxOverride = ButtonBox(color);
    }

    /// <summary>
    /// Toggles a styled button's enabled state, dimming it while disabled (the flat stylebox
    /// override doesn't grey out on its own).
    /// </summary>
    private static void SetEnabled(Button button, bool enabled)
    {
        button.Disabled = !enabled;
        // Keep the color clearly readable even when disabled (matches the always-vivid mockup).
        button.Modulate = enabled ? Color.White : new Color(0.82f, 0.82f, 0.82f);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (!disposing)
            return;

        _mediaPlayer.SearchReceived -= OnSearchReceived;
        _mediaPlayer.StatusReceived -= OnStatusReceived;
        _mediaPlayer.StateUpdated -= UpdateNowPlaying;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_mediaPlayer.IsPlaying)
        {
            ProgressBar.Value = 0f;
            return;
        }

        var position = _mediaPlayer.CurrentPosition;
        var duration = _mediaPlayer.CurrentDuration;

        ProgressBar.MaxValue = duration > 0 ? duration : 1f;
        ProgressBar.Value = Math.Clamp(position, 0f, ProgressBar.MaxValue);

        TimeCurrentLabel.Text = FormatTime(position);
        TimeTotalLabel.Text = FormatTime(duration);
    }

    private void Search()
    {
        var query = SearchField.Text.Trim();
        if (query.Length == 0)
            return;

        SetSearching(true);
        _mediaPlayer.RequestSearch(query);
    }

    private void SetSearching(bool searching)
    {
        SearchButton.Disabled = searching;
        SearchButton.Text = Loc.GetString(searching
            ? "ui-media-player-searching-button"
            : "ui-media-player-search-button");

        if (searching)
        {
            StatusLabel.Text = Loc.GetString("ui-media-player-searching");
            StatusLabel.FontColorOverride = SearchingColor;
        }
        else
        {
            StatusLabel.FontColorOverride = null;
        }
    }

    private void PlayOrPause()
    {
        var state = _mediaPlayer.LastState;
        if (state?.TrackId != null)
        {
            // Track is loaded: toggle pause/resume on the server.
            _mediaPlayer.RequestPause();
            return;
        }

        PlaySelected();
    }

    private void PlaySelected()
    {
        foreach (var item in ResultsList.GetSelected())
        {
            var index = ResultsList.IndexOf(item);
            if (index >= 0 && index < _results.Count)
                _mediaPlayer.RequestPlay(_results[index].Id);
            return;
        }
    }

    private void PlayUrl()
    {
        var url = SearchField.Text.Trim();
        if (url.Length == 0)
            return;

        _mediaPlayer.RequestPlay(url);
    }

    private void OnSearchReceived(MediaPlayerSearchResponseEvent ev)
    {
        ResultsList.Clear();
        SetEnabled(PlayPauseButton, false);
        _results = _mediaPlayer.LastSearchResults;
        SetSearching(false);

        if (ev.Error != null)
        {
            StatusLabel.Text = ev.Error;
            StatusLabel.FontColorOverride = ErrorColor;
            return;
        }

        StatusLabel.Text = Loc.GetString("ui-media-player-results", ("count", _results.Count));
        PopulateResultsList();
    }

    private void PopulateResultsList()
    {
        ResultsList.Clear();
        foreach (var result in _results)
        {
            var title = MediaPlayerSystem.SanitizeTitle(result.Title);
            var uploader = result.Uploader.Length > 0
                ? $" — {MediaPlayerSystem.SanitizeTitle(result.Uploader)}"
                : "";
            ResultsList.AddItem($"[{FormatTime(result.DurationSeconds)}] {title}{uploader}");
        }
    }

    private void OnStatusReceived(MediaPlayerStatusEvent ev)
    {
        StatusLabel.Text = ev.Message;
        StatusLabel.FontColorOverride = ev.IsError ? ErrorColor : WorkingColor;
    }

    private void UpdateNowPlaying()
    {
        var state = _mediaPlayer.LastState;

        // Nothing loaded.
        if (state?.TrackId == null)
        {
            NowPlayingLabel.Text = Loc.GetString("ui-media-player-nothing");
            TimeCurrentLabel.Text = FormatTime(0);
            TimeTotalLabel.Text = FormatTime(0);
            ProgressBar.Value = 0f;
            SetEnabled(PlayPauseButton, false);
            SetEnabled(StopButton, false);
            PlayPauseButton.Text = Loc.GetString("ui-media-player-play-button");
            return;
        }

        // A track is loaded (playing or paused): clear the transient status line.
        StatusLabel.Text = string.Empty;

        NowPlayingLabel.Text = MediaPlayerSystem.SanitizeTitle(state.Title);
        TimeTotalLabel.Text = FormatTime(state.Duration);
        SetEnabled(PlayPauseButton, true);
        SetEnabled(StopButton, true);
        PlayPauseButton.Text = Loc.GetString(state.Playing
            ? "ui-media-player-pause-button"
            : "ui-media-player-resume-button");
    }

    private void UpdateVolumeLabel(float value)
    {
        VolumePercentLabel.Text = $"{(int)MathF.Round(value * 100f)}%";
    }

    private static string FormatTime(float seconds)
    {
        var span = TimeSpan.FromSeconds(Math.Max(0f, seconds));
        return span.TotalHours >= 1
            ? $"{(int)span.TotalHours}:{span.Minutes:00}:{span.Seconds:00}"
            : $"{span.Minutes}:{span.Seconds:00}";
    }
}
