using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.MediaPlayer.UI;

/// <summary>
/// Small HUD indicator that shows the currently playing media-player track.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MediaPlayerIndicator : UIWidget
{
    private const int MaxTitleLength = 40;

    public MediaPlayerIndicator()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTrack(string title)
    {
        if (title.Length > MaxTitleLength)
            title = title[..MaxTitleLength] + "…";

        TitleLabel.Text = title;
    }
}
