using System.Numerics;
using Content.Shared._Wega.Magic.LoveCurse;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.Magic.LoveCurse;

[GenerateTypedNameReferences]
public sealed partial class LoveCursePanel : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IEntityNetworkManager _entityNetworkManager = default!;

    private NetEntity _caster;

    public LoveCursePanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(NetEntity caster)
    {
        _caster = caster;
        TargetsContainer.RemoveAllChildren();

        var query = _entityManager.EntityQueryEnumerator<MetaDataComponent, HumanoidProfileComponent>();
        while (query.MoveNext(out var uid, out var meta, out _))
        {
            // Don't show the caster themselves
            if (_entityManager.GetNetEntity(uid) == caster)
                continue;

            var button = new Button
            {
                Text = meta.EntityName,
                HorizontalAlignment = HAlignment.Center,
                MinSize = new Vector2(300, 32),
                MaxSize = new Vector2(300, 32),
            };

            var netUid = _entityManager.GetNetEntity(uid);
            button.OnPressed += _ =>
            {
                _entityNetworkManager.SendSystemNetworkMessage(
                    new LoveCurseTargetSelectedEvent(_caster, netUid));
                Close();
            };

            TargetsContainer.AddChild(button);
        }
    }
}
