[net]
port = 1212
bindto = "0.0.0.0"
tickrate = 30
max_connections = 64

[status]
enabled = true

[game]
hostname = "Wega Mega"

[auth]
mode = 1
allowlocal = false

[hub]
advertise = false

[console]
loginlocal = false

[database]
engine = "sqlite"
sqlite_dbpath = "preferences.db"

[wega]
allowed_account_ids = "CE5DA150-683B-4EAE-9B2E-59DEC887F527,A79BC02F-A745-4D2A-AEAF-2D5D612F93A2"
update_notice_file = "/var/lib/wega/data/update-pending"

[log]
enabled = false
