#!/usr/bin/env python3
"""Генерирует АНИМИРОВАННЫЙ голографический спрайт «ОЖИДАНИЕ» для дуэльного индикатора ожидания.

Оранжевая версия голограммы «ГОТОВ» (см. Tools/gen_duel_ready_hologram.py): неон переливается
янтарный↔оранжевый, по тексту бежит яркая скан-линия, есть лёгкий тёплый хроматический сдвиг и
редкий глитч-фликер. Висит над кнопкой бойца, который УЖЕ нажал готовность и ждёт соперника.
Кадры пакуются вертикально в один лист icon.png; тайминги — в meta.json. В игре рисуется
unshaded + оранжевый PointLight (см. прототип DuelWaitingHologram).

Запуск из корня репозитория:  python3 Tools/gen_duel_waiting_hologram.py
"""
import json
import math
import os

from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = os.path.join(os.path.dirname(__file__), "..")
FONT = os.path.join(ROOT, "Resources", "Fonts", "NotoSans", "NotoSans-Bold.ttf")
RSI = os.path.join(ROOT, "Resources", "Textures", "_Wega", "Effects", "duel_waiting.rsi")

W, H = 128, 32           # шире «ГОТОВ» (96px): «ОЖИДАНИЕ» — 8 символов
TEXT = "ОЖИДАНИЕ"
FRAMES = 12              # кадров в цикле
DELAY = 0.08            # секунд на кадр (~0.96с цикл)

AMBER = (255, 190, 70)   # неоново-янтарный
ORANGE = (255, 120, 30)  # неоново-оранжевый
GLOW_A = (230, 140, 40)  # свечение (янтарь)
GLOW_O = (210, 90, 20)   # свечение (оранж)


def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(len(a)))


def fit_font(text, max_w, max_h):
    """Подбирает максимальный кегль, при котором текст влезает в (max_w, max_h)."""
    size = 30
    while size > 8:
        font = ImageFont.truetype(FONT, size)
        l, t, r, b = font.getbbox(text)
        if (r - l) <= max_w and (b - t) <= max_h:
            return font
        size -= 1
    return ImageFont.truetype(FONT, 8)


def make_frame(font, x, y, f):
    """Строит один кадр анимации (RGBA W×H) для фазы f/FRAMES."""
    phase = f / FRAMES
    # Переливание цвета: плавная синусоида янтарный↔оранжевый.
    osc = 0.5 + 0.5 * math.sin(phase * 2 * math.pi)
    bright = lerp(AMBER, ORANGE, osc)
    glow = lerp(GLOW_A, GLOW_O, osc)

    frame = Image.new("RGBA", (W, H), (0, 0, 0, 0))

    # Bloom: размытый цветной текст, наложенный дважды.
    glow_img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(glow_img).text((x, y), TEXT, font=font, fill=glow + (170,))
    glow_img = glow_img.filter(ImageFilter.GaussianBlur(2.4))
    frame.alpha_composite(glow_img)
    frame.alpha_composite(glow_img)

    # Хроматический сдвиг (RGB-split): тёплые смещённые копии (красный/жёлтый).
    # Смещение чуть «дышит» по фазе — эффект нестабильной голограммы.
    shift = 1 + (1 if (f % 4 == 0) else 0)
    red = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(red).text((x - shift, y), TEXT, font=font, fill=(255, 60, 20, 70))
    frame.alpha_composite(red)
    yel = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(yel).text((x + shift, y), TEXT, font=font, fill=(255, 220, 90, 70))
    frame.alpha_composite(yel)

    # Чёткий яркий текст поверх.
    ImageDraw.Draw(frame).text((x, y), TEXT, font=font, fill=bright + (255,))

    px = frame.load()

    # Статичные голо-сканлайны: каждую вторую строку гасим.
    for yy in range(0, H, 2):
        for xx in range(W):
            cr, cg, cb, ca = px[xx, yy]
            if ca:
                px[xx, yy] = (cr, cg, cb, int(ca * 0.7))

    # Бегущая яркая скан-линия (двигается вниз по кадрам).
    band = int(phase * H)
    for yy in (band, (band + 1) % H):
        for xx in range(W):
            cr, cg, cb, ca = px[xx, yy]
            if ca:
                px[xx, yy] = (min(255, cr + 90), min(255, cg + 90),
                              min(255, cb + 90), min(255, ca + 45))

    # Глитч-фликер: один кадр в цикле — резко тусклее (голограмма «моргает»).
    if f == FRAMES - 2:
        for yy in range(H):
            for xx in range(W):
                cr, cg, cb, ca = px[xx, yy]
                if ca:
                    px[xx, yy] = (cr, cg, cb, int(ca * 0.4))

    return frame


def main():
    os.makedirs(RSI, exist_ok=True)
    font = fit_font(TEXT, W - 8, H - 8)

    # Центрируем по фактическому bbox (NotoSans даёт верхний отступ).
    l, t, r, b = font.getbbox(TEXT)
    tw, th = r - l, b - t
    x = (W - tw) / 2 - l
    y = (H - th) / 2 - t

    # Лист кадров: один столбец (ширина = W), кадры сверху вниз.
    sheet = Image.new("RGBA", (W, H * FRAMES), (0, 0, 0, 0))
    for f in range(FRAMES):
        sheet.alpha_composite(make_frame(font, x, y, f), (0, f * H))
    sheet.save(os.path.join(RSI, "icon.png"))

    meta = {
        "version": 1,
        "license": "CC0-1.0",
        "copyright": "Generated by Tools/gen_duel_waiting_hologram.py (NotoSans-Bold text, animated cyberpunk hologram)",
        "size": {"x": W, "y": H},
        "states": [{"name": "icon", "delays": [[DELAY] * FRAMES]}],
    }
    with open(os.path.join(RSI, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"written {os.path.join(RSI, 'icon.png')} "
          f"({W}x{H*FRAMES}, {FRAMES} frames @ {DELAY}s), font size {font.size}")


if __name__ == "__main__":
    main()
