#!/usr/bin/env python3
"""Генерирует голографический спрайт «ГОТОВ» для индикатора готовности дуэли.

Ярко-зелёное слово «ГОТОВ» (NotoSans-Bold) с мягким зелёным свечением (bloom) и
лёгкими сканлайнами — голографический вид. В игре рисуется unshaded + зелёный
PointLight (см. прототип DuelReadyHologram).

Запуск из корня репозитория:  python3 Tools/gen_duel_ready_hologram.py
"""
import json
import os

from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = os.path.join(os.path.dirname(__file__), "..")
FONT = os.path.join(ROOT, "Resources", "Fonts", "NotoSans", "NotoSans-Bold.ttf")
RSI = os.path.join(ROOT, "Resources", "Textures", "_Wega", "Effects", "duel_ready.rsi")

W, H = 96, 32
TEXT = "ГОТОВ"
BRIGHT = (90, 255, 120, 255)   # ярко-зелёный
GLOW = (40, 200, 80)           # цвет свечения


def fit_font(text, max_w, max_h):
    """Подбирает максимальный кегль, при котором текст влезает в (max_w, max_h)."""
    size = 30
    while size > 8:
        font = ImageFont.truetype(FONT, size)
        l, t, r, b = font.getbbox(text)
        if (r - l) <= max_w and (b - t) <= max_h:
            return font
        size -= 1
    return ImageFont.truetype(FONT, 8)


def main():
    os.makedirs(RSI, exist_ok=True)
    font = fit_font(TEXT, W - 8, H - 8)

    # Центрируем по фактическому bbox (NotoSans даёт верхний отступ).
    l, t, r, b = font.getbbox(TEXT)
    tw, th = r - l, b - t
    x = (W - tw) / 2 - l
    y = (H - th) / 2 - t

    # Слой свечения: текст в полупрозрачном зелёном, размытый — bloom.
    glow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    gd.text((x, y), TEXT, font=font, fill=GLOW + (180,))
    glow = glow.filter(ImageFilter.GaussianBlur(2.2))

    out = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    out.alpha_composite(glow)
    out.alpha_composite(glow)  # удвоить свечение

    # Чёткий яркий текст поверх.
    od = ImageDraw.Draw(out)
    od.text((x, y), TEXT, font=font, fill=BRIGHT)

    # Голо-сканлайны: каждую вторую строку слегка гасим.
    px = out.load()
    for yy in range(0, H, 2):
        for xx in range(W):
            cr, cg, cb, ca = px[xx, yy]
            if ca:
                px[xx, yy] = (cr, cg, cb, int(ca * 0.72))

    out.save(os.path.join(RSI, "icon.png"))

    meta = {
        "version": 1,
        "license": "CC0-1.0",
        "copyright": "Generated by Tools/gen_duel_ready_hologram.py (NotoSans-Bold text)",
        "size": {"x": W, "y": H},
        "states": [{"name": "icon"}],
    }
    with open(os.path.join(RSI, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"written {os.path.join(RSI, 'icon.png')} ({W}x{H}), font size {font.size}")


if __name__ == "__main__":
    main()
