#!/usr/bin/env python3
"""Генерирует АНИМИРОВАННЫЙ киберпанк-шрифт цифр для дуэльного таймера отсчёта.

Тот же стиль, что у голограммы «ГОТОВ» (Tools/gen_duel_ready_hologram.py): NotoSans-Bold,
неон переливается зелёный↔циан, голо-сканлайны, мягкое свечение (bloom) и редкий глитч-фликер.
Каждый символ — отдельный state в RSI, кадры пакуются вертикально; тайминги — в meta.json.
Цвета ЗАШИТЫ в кадры (модуляция в игре = White), поэтому таймер ставит color: White + shader: unshaded.

Глифы выровнены по общей базовой линии (цифры и двоеточие не «прыгают»). Набор символов —
ровно то, что показывает отсчёт MM:SS / SS:cs: цифры 0–9, двоеточие, тире и пустой (blank).

Запуск из корня репозитория:  python3 Tools/gen_duel_timer_font.py
"""
import json
import math
import os

from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = os.path.join(os.path.dirname(__file__), "..")
FONT = os.path.join(ROOT, "Resources", "Fonts", "NotoSans", "NotoSans-Bold.ttf")
RSI = os.path.join(ROOT, "Resources", "Textures", "_Wega", "Effects", "duel_timer_text.rsi")

GLYPH_W, GLYPH_H = 6, 12   # размер одного глифа (px); под него CharWidth=5 у таймера (влезает в табло 32px)
FRAMES = 12
DELAY = 0.08

GREEN = (120, 255, 140)
CYAN = (80, 240, 255)
GLOW_G = (40, 220, 120)
GLOW_C = (40, 180, 230)

# Символ -> имя state (как в Effects/text.rsi: спецсимволы зовутся словами).
CHARS = {
    "0": "0", "1": "1", "2": "2", "3": "3", "4": "4",
    "5": "5", "6": "6", "7": "7", "8": "8", "9": "9",
    ":": "colon", "-": "dash",
}


def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(len(a)))


def fit_font():
    """Максимальный кегль NotoSans-Bold, при котором цифра «0» влезает в глиф с отступом."""
    size = GLYPH_H
    while size > 6:
        font = ImageFont.truetype(FONT, size)
        l, t, r, b = font.getbbox("0")
        if (r - l) <= GLYPH_W - 1 and (b - t) <= GLYPH_H - 1:
            return font
        size -= 1
    return ImageFont.truetype(FONT, 6)


def make_glyph_frame(font, ch, baseline_y, f):
    """Один кадр символа (RGBA GLYPH_W×GLYPH_H) в стиле голограммы."""
    phase = f / FRAMES
    osc = 0.5 + 0.5 * math.sin(phase * 2 * math.pi)
    bright = lerp(GREEN, CYAN, osc)
    glow = lerp(GLOW_G, GLOW_C, osc)

    cx = GLYPH_W / 2.0
    frame = Image.new("RGBA", (GLYPH_W, GLYPH_H), (0, 0, 0, 0))

    # Bloom: размытая подложка, наложенная дважды.
    glow_img = Image.new("RGBA", (GLYPH_W, GLYPH_H), (0, 0, 0, 0))
    ImageDraw.Draw(glow_img).text((cx, baseline_y), ch, font=font, fill=glow + (180,), anchor="ms")
    glow_img = glow_img.filter(ImageFilter.GaussianBlur(1.1))
    frame.alpha_composite(glow_img)
    frame.alpha_composite(glow_img)

    # Чёткий яркий символ.
    ImageDraw.Draw(frame).text((cx, baseline_y), ch, font=font, fill=bright + (255,), anchor="ms")

    px = frame.load()
    # Голо-сканлайны: каждую вторую строку гасим (читаемость сохраняем).
    for yy in range(0, GLYPH_H, 2):
        for xx in range(GLYPH_W):
            cr, cg, cb, ca = px[xx, yy]
            if ca:
                px[xx, yy] = (cr, cg, cb, int(ca * 0.72))

    # Глитч-фликер: один кадр в цикле заметно тусклее.
    if f == FRAMES - 2:
        for yy in range(GLYPH_H):
            for xx in range(GLYPH_W):
                cr, cg, cb, ca = px[xx, yy]
                if ca:
                    px[xx, yy] = (cr, cg, cb, int(ca * 0.45))

    return frame


def write_state(name, sheet):
    sheet.save(os.path.join(RSI, f"{name}.png"))


def main():
    os.makedirs(RSI, exist_ok=True)
    font = fit_font()

    # Общая базовая линия: центрируем вертикальный размер шрифта в глифе.
    ascent, descent = font.getmetrics()
    baseline_y = (GLYPH_H - (ascent + descent)) / 2.0 + ascent

    states = []
    for ch, name in CHARS.items():
        sheet = Image.new("RGBA", (GLYPH_W, GLYPH_H * FRAMES), (0, 0, 0, 0))
        for f in range(FRAMES):
            sheet.alpha_composite(make_glyph_frame(font, ch, baseline_y, f), (0, f * GLYPH_H))
        write_state(name, sheet)
        states.append({"name": name, "delays": [[DELAY] * FRAMES]})

    # Пустой символ (пробел/дефолт) — прозрачный, один кадр.
    write_state("blank", Image.new("RGBA", (GLYPH_W, GLYPH_H), (0, 0, 0, 0)))
    states.append({"name": "blank"})

    meta = {
        "version": 1,
        "license": "CC0-1.0",
        "copyright": "Generated by Tools/gen_duel_timer_font.py (NotoSans-Bold digits, animated cyberpunk hologram)",
        "size": {"x": GLYPH_W, "y": GLYPH_H},
        "states": states,
    }
    with open(os.path.join(RSI, "meta.json"), "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    print(f"written {RSI}: {len(states)} states, {GLYPH_W}x{GLYPH_H} glyphs, "
          f"{FRAMES} frames @ {DELAY}s, font size {font.size}")


if __name__ == "__main__":
    main()
